insert into car (car_model, company_name, price) values ('MR2', 'Toyota', 36795);
insert into car (car_model, company_name, price) values ('Eclipse', 'Mitsubishi', 49214);
insert into car (car_model, company_name, price) values ('SLK-Class', 'Mercedes-Benz', 48373);
insert into car (car_model, company_name, price) values ('Montero Sport', 'Mitsubishi', 58513);
insert into car (car_model, company_name, price) values ('Continental Flying Spur', 'Bentley', 64721);
insert into car (car_model, company_name, price) values ('Escalade EXT', 'Cadillac', 56976);
insert into car (car_model, company_name, price) values ('3500', 'GMC', 78710);
insert into car (car_model, company_name, price) values ('Corvette', 'Chevrolet', 74328);
insert into car (car_model, company_name, price) values ('Concorde', 'Chrysler', 36485);
insert into car (car_model, company_name, price) values ('GTI', 'Volkswagen', 97353);
insert into car (car_model, company_name, price) values ('Arnage', 'Bentley', 88268);
insert into car (car_model, company_name, price) values ('Golf', 'Volkswagen', 45232);
insert into car (car_model, company_name, price) values ('Dakota', 'Dodge', 36248);
insert into car (car_model, company_name, price) values ('Solstice', 'Pontiac', 33949);
insert into car (car_model, company_name, price) values ('Sephia', 'Kia', 30101);
insert into car (car_model, company_name, price) values ('207', 'Peugeot', 73057);
insert into car (car_model, company_name, price) values ('Aveo', 'Chevrolet', 40852);
insert into car (car_model, company_name, price) values ('Rally Wagon G2500', 'GMC', 73299);
insert into car (car_model, company_name, price) values ('Firefly', 'Pontiac', 49345);
insert into car (car_model, company_name, price) values ('Pacifica', 'Chrysler', 46451);
insert into car (car_model, company_name, price) values ('Sienna', 'Toyota', 96694);
insert into car (car_model, company_name, price) values ('GLI', 'Volkswagen', 75477);
insert into car (car_model, company_name, price) values ('Aerostar', 'Ford', 91267);
insert into car (car_model, company_name, price) values ('XC90', 'Volvo', 69387);
insert into car (car_model, company_name, price) values ('A6', 'Audi', 86300);
insert into car (car_model, company_name, price) values ('Sonoma Club Coupe', 'GMC', 98275);
insert into car (car_model, company_name, price) values ('LTD Crown Victoria', 'Ford', 57081);
insert into car (car_model, company_name, price) values ('Caprice', 'Chevrolet', 79136);
insert into car (car_model, company_name, price) values ('Viper RT/10', 'Dodge', 48891);
insert into car (car_model, company_name, price) values ('Tempo', 'Ford', 74511);
